# Cloud Build configuration for FastAPI backend
# Automatically build and deploy on git push

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/genai-fastapi-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/genai-fastapi-backend:latest'
      - '.'
    dir: 'services/fastapi-backend'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/genai-fastapi-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/genai-fastapi-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'genai-fastapi-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/genai-fastapi-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,VERTEX_AI_LOCATION=us-central1,FASTAPI_ENV=production,LOG_LEVEL=info,CORS_ORIGINS=*,DEFAULT_MODEL=gemini-2.5-flash,DD_SERVICE=genai-fastapi-backend,DD_ENV=production,DD_VERSION=$SHORT_SHA,DD_LOGS_ENABLED=true,DD_LOGS_INJECTION=true,DD_SOURCE=python,DD_TRACE_SAMPLE_RATE=1.0,DD_TRACE_ENABLED=1,DD_PROFILING_ENABLED=true'

images:
  - 'gcr.io/$PROJECT_ID/genai-fastapi-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/genai-fastapi-backend:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

